language: java
env:
- NODE_VERSION="12.13.1"
services:
- docker
addons:
  sonarcloud:
    organization: "mohsen-hn"

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - node_modules

#safelist
branches:
  only:
    - develop

jobs:
  include:
  - stage: Prepare
    script:
      - mvn clean sonar:sonar -Dsonar.projectKey=Mohsen-HN_projet_informatique-moviet2 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=bf879cc0b2bcfcb47ffac4bbe4eb6ff2859100d8
