apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui-deployment
  labels:
    app: web-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
      - name: web-ui
        image: web-ui
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4200
